version: "3"

services:
  client-web:
    image: node:10.15.3-stretch-slim
    container_name: web
    volumes:
      - ./client-app:/client-app
    working_dir: /client-app
    command: npm run serve
    ports:
      - 80:8080
    networks:
      - default

  socket:
    image: node:10.15.3-stretch-slim
    container_name: socket
    volumes:
      - ./api/socket-io:/socket
    working_dir: /socket
    command: npm start
    ports:
      - 9000:9000
    networks:
      - default

  # web:
  #   image: nginx
  #   container_name: web_build
  #   volumes:
  #     - ./client-app/dist:/usr/share/nginx/html                     # html file
  #     - ./client-app/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf  # config file
  #     - ./client-app/nginx/cert:/etc/letsencrypt  
  #   ports:
  #     - 80:80
  #     - 443:443

  ###########################
  #      api แต่ละ org
  ########################### 
  donator-api:
    image: node:10.15.3-stretch-slim
    container_name: donator-api
    environment:
      - ORG=Org1
      - HOST_IP=192.168.1.2 # ip ของเครื่องที่เรารันอยู่ สำหรับทำ qr
      - NODE_ENV=docker
      - CCP=connection.docker.json
      - GOOGLE_APPLICATION_CREDENTIALS=/cert/donate-project-key.json # Google gcp in container
    volumes:
      - ./api/api_v2:/app
      - ./api/wallet1:/wallet1
      - ../cert:/cert # map Google gcp cert on server to container
      - ./client-app/nginx/cert:/etc/letsencrypt
    working_dir: /app
    command: npm start
    ports:
      - 8000:8000
    networks:
      - default

  creator-api:
    image: node:10.15.3-stretch-slim
    container_name: creator-api
    environment:
      - NODE_ENV=docker
      - ORG=Org2
      - CCP=connection.docker.json
      - GOOGLE_APPLICATION_CREDENTIALS=/cert/donate-project-key.json # Google gcp in container
    volumes:
      - ./api/api_v2:/app
      - ./api/wallet2:/wallet2
      - ../cert:/cert # map Google gcp cert on server to container
      - ./client-app/nginx/cert:/etc/letsencrypt
    working_dir: /app
    command: npm start
    ports:
      - 8001:8001
    networks:
      - default
  
  receiver-api:
    image: node:10.15.3-stretch-slim
    container_name: receiver-api
    environment:
      - NODE_ENV=docker
      - ORG=Org3
      - CCP=connection.docker.json
      - GOOGLE_APPLICATION_CREDENTIALS=/cert/donate-project-key.json # Google gcp in container
    volumes:
      - ./api/api_v2:/app
      - ./api/wallet3:/wallet3
      - ../cert:/cert # map Google gcp cert on server to container
      - ./client-app/nginx/cert:/etc/letsencrypt
    working_dir: /app
    command: npm start
    ports:
      - 8002:8002
    networks:
      - default

  ###########################
  # Mock revenue department
  ###########################
  revenue-api:
    image: node:10.15.3-stretch-slim
    container_name: revenue-api
    environment:
      - NODE_ENV=docker
    volumes:
      - ./api/revenue-api:/app
    working_dir: /app
    command: npm start
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
    external:
      name: netdonate_basic
