version: "3"

services:
  #####################
  #   User Interface
  #####################
  client-web:
    container_name: bc-web
    image: sumrid/bc_client-web:v1
    build: ./web/client-app
    ports:
      - 80:80
    networks:
      - bc-network

  dashboard:
    container_name: bc-dashboard
    image: sumrid/bc_dashboard:v1
    build: ./web/dashboard-ui
    ports:
      - 81:80
    networks:
      - bc-network

  store:
    container_name: bc-store
    image: sumrid/bc_store:v1
    build: ./web/store
    ports:
      - 82:80
    networks:
      - bc-network

  socket:
    container_name: bc-socket
    image: sumrid/bc_socket-io:v1
    build: ./api/socket-io
    ports:
      - 9000:9000
    networks:
      - bc-network

  #####################
  #        API
  #####################
  donator-api:
    container_name: bc-donator-api
    image: sumrid/bc_api:v1
    build: ./api/api_v2
    environment:
      - ORG=Org1
      - NODE_ENV=docker
      # - HOST_IP=00.00.00.00
      - CCP=connection.docker.json
      - FIREBASE_KEY=/cert/firebase/adminKey.json
    volumes:
      - ./api/wallet1:/wallet1
      - ./cert:/cert
    ports:
      - 8000:8000
    networks:
      - bc-network

  creator-api:
    container_name: bc-creator-api
    image: sumrid/bc_api:v1
    build: ./api/api_v2
    environment:
      - ORG=Org2
      - NODE_ENV=docker
      - CCP=connection.docker.json
      - FIREBASE_KEY=/cert/firebase/adminKey.json
    volumes:
      - ./api/wallet2:/wallet2
      - ./cert:/cert
    ports:
      - 8001:8001
    networks:
      - bc-network

  receiver-api:
    container_name: bc-receiver-api
    image: sumrid/bc_api:v1
    build: ./api/api_v2
    environment:
      - ORG=Org3
      - NODE_ENV=docker
      - CCP=connection.docker.json
      - FIREBASE_KEY=/cert/firebase/adminKey.json
    volumes:
      - ./api/wallet3:/wallet3
      - ./cert:/cert
    ports:
      - 8002:8002
    networks:
      - bc-network

  ##########################
  # Mock revenue department
  ##########################
  revenue-api:
    container_name: bc-revenue-api
    image: sumrid/bc_revenue-api:v1
    build: ./api/revenue-api
    environment:
      - NODE_ENV=docker
      - FIREBASE_KEY=/cert/firebase/adminKey.json
    volumes:
      - ./cert:/cert
    ports:
      - 8080:8080
    networks:
      - bc-network

networks:
  bc-network:
    external:
      name: netdonate_basic
