version: '3'

services: 
  api:
    image: node:10.15.3-stretch-slim
    container_name: api
    environment: 
      - DB_URL=mongodb://db:27017
      - HOST_IP=35.198.196.72
      - NODE_ENV=docker
    volumes: 
      - ./api/api_v2:/app
      - ./api/wallet1:/wallet1
      - ./api/wallet2:/wallet2
    working_dir: /app
    command: npm start
    ports: 
      - 8000:8000
    depends_on: 
      - db
    networks: 
      - default

  client-web:
    image: node:10.15.3-stretch-slim
    container_name: web
    volumes: 
      - ./client-app:/client-app
    working_dir: /client-app
    command: npm run serve
    ports: 
      - 8080:8080
    networks: 
      - default
      
  # web:
  #   image: nginx
  #   volumes: 
  #     - ./client-app/dist:/usr/share/nginx/html
  #   ports: 
  #     - 8080:80

  db:
    image: mongo:4.0.11-xenial
    container_name: mongo
    volumes: 
      - ./data/db:/data/db
    ports: 
      - 27017:27017
    networks: 
      - default

networks:
  default:
    external: 
      name: netdonate_basic